---
- name: Install Elasticsearch
  hosts: el-instance
  roles:
    - elastic

- name: Install Kibana
  hosts: k-instance
  roles:
    - kibana-role

- name: Install Filebeat
  hosts: f-instance
  roles:
    - filebeat-role